version: '2.13' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: front # specify the directory of the Dockerfile
  ports:
  - "4200:80" # specify port mapping
 
 express: # name of the second service
  build: backend # specify the directory of the Dockerfile
  ports:
    - "5000:8090" #specify ports mapping
  
  links:
    - mongo # link this service to the database service
  depends_on:
    - mongo
  restart: always
 
 mongo:
  container_name: mongo
  image: mongo
  ports:
    - '27017:27017'
    